<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net45;net462;netstandard2.0;net5.0;net6.0</TargetFrameworks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>KaitoKid</Authors>
        <Version>3.1.16</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
		<Description>.NET library for Interface Utilities</Description>
		<PackageProjectUrl>https://github.com/agilbert1412/ArchipelagoUtilities/blob/main/README.md</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/agilbert1412/ArchipelagoUtilities</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

    <Target Name="Copy nuget to release folder" AfterTargets="Pack">
        <Message Text="Copying the nuget package to the release folder" Importance="High" />
        <Copy SourceFiles="$(OutputPath)KaitoKid.Utilities.Interfaces.$(Version).nupkg" DestinationFolder="..\..\Release" ContinueOnError="false" />
        <Message Text="Copied nuget package" Importance="High" />
    </Target>

</Project>