<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net45;net462;netstandard2.0;net5.0;net6.0</TargetFrameworks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>KaitoKid</Authors>
        <Version>3.1.16</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
		<Description>.NET library for Archipelago Utilities</Description>
		<PackageProjectUrl>https://github.com/agilbert1412/ArchipelagoUtilities/blob/main/README.md</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/agilbert1412/ArchipelagoUtilities</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\.editorconfig" Link=".editorconfig" />
		<Content Include="Custom Assets\**\*">
			<Pack>true</Pack>
			<PackageCopyToOutput>true</PackageCopyToOutput>
		</Content>
	</ItemGroup>
	<ItemGroup Condition="$(TargetFramework.StartsWith('netcore'))">

	</ItemGroup>
	<ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">

	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Archipelago.MultiClient.Net" Version="6.6.0" />
		<PackageReference Include="Archipelago.MultiClient.Net.Analyzers" Version="1.1.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\KaitoKid.Utilities.Interfaces\KaitoKid.Utilities.Interfaces.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Custom Assets\*\*">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

    <Target Name="Copy nuget to release folder" AfterTargets="Pack">
        <Message Text="Copying the nuget package to the release folder" Importance="High" />
        <Copy SourceFiles="$(OutputPath)KaitoKid.ArchipelagoUtilities.Net.$(Version).nupkg" DestinationFolder="..\..\Release" ContinueOnError="false" />
        <Message Text="Copied nuget package" Importance="High" />
    </Target>

</Project>